spring:
  datasource:
    url: jdbc:mysql://localhost:3306/taskdb?useSSL=false
    username: root
    password: root@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

    # Automatically update the database schema
    hibernate:
      ddl-auto: update
